import os
import smtplib
import ssl
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


def _score_badge(score: int) -> str:
    if score >= 9:
        color = "#1a7f37"
        bg = "#d4edda"
    elif score >= 7:
        color = "#856404"
        bg = "#fff3cd"
    elif score >= 5:
        color = "#0c5460"
        bg = "#d1ecf1"
    else:
        color = "#6c757d"
        bg = "#f8f9fa"
    return (
        f'<span style="display:inline-block;padding:2px 8px;border-radius:12px;'
        f'font-size:12px;font-weight:700;color:{color};background:{bg};">'
        f"{score}/10</span>"
    )


def _article_block(art: dict) -> str:
    badge = _score_badge(art["score"])
    return f"""
<div style="margin-bottom:28px;padding-bottom:20px;border-bottom:1px solid #e9ecef;">
  <div style="margin-bottom:6px;">
    {badge}
    <span style="font-size:12px;color:#6c757d;margin-left:8px;">{art['source']} &middot; {art['published']}</span>
  </div>
  <a href="{art['url']}" style="font-size:17px;font-weight:600;color:#1a1a2e;text-decoration:none;line-height:1.4;">
    {art['title']}
  </a>
  <p style="margin:8px 0 0;font-size:14px;color:#444;line-height:1.6;">{art['summary']}</p>
</div>
"""


SECTIONS = [
    ("india",       "🇮🇳 AI in Indian Enterprise, BFSI &amp; Regulation"),
    ("global_bfsi", "🌐 Global BFSI AI"),
    ("startups",    "💡 Novel AI Use Cases &amp; Startups"),
]


def _section_header(label: str) -> str:
    return (
        f'<div style="margin:8px 0 20px;padding-bottom:8px;border-bottom:2px solid #1a1a2e;">'
        f'<span style="font-size:15px;font-weight:700;color:#1a1a2e;">{label}</span>'
        f'</div>'
    )


def build_html(articles: list[dict], total_fetched: int, source_count: int) -> str:
    today = date.today().strftime("%d %B %Y")

    # Group by section, preserving score-sorted order within each section
    grouped = {key: [] for key, _ in SECTIONS}
    for art in articles:
        sec = art.get("section", "startups")
        if sec not in grouped:
            sec = "startups"
        grouped[sec].append(art)

    section_html = ""
    for key, label in SECTIONS:
        arts = grouped[key]
        if not arts:
            continue
        section_html += _section_header(label)
        section_html += "".join(_article_block(a) for a in arts)

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body style="margin:0;padding:0;background:#f4f6f9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f6f9;padding:24px 0;">
  <tr>
    <td align="center">
      <table width="640" cellpadding="0" cellspacing="0" style="max-width:640px;width:100%;background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);">

        <!-- Header -->
        <tr>
          <td style="background:#1a1a2e;padding:28px 32px;">
            <div style="font-size:11px;color:#8892a4;letter-spacing:2px;text-transform:uppercase;margin-bottom:4px;">Daily Digest</div>
            <div style="font-size:22px;font-weight:700;color:#ffffff;">Enterprise AI &middot; India &amp; FinServ</div>
            <div style="font-size:13px;color:#8892a4;margin-top:4px;">{today}</div>
          </td>
        </tr>

        <!-- Stats bar -->
        <tr>
          <td style="background:#f8f9fc;padding:12px 32px;border-bottom:1px solid #e9ecef;">
            <span style="font-size:12px;color:#6c757d;">
              {len(articles)} articles &nbsp;&middot;&nbsp; from {source_count} sources &nbsp;&middot;&nbsp; {total_fetched} total reviewed
            </span>
          </td>
        </tr>

        <!-- Articles -->
        <tr>
          <td style="padding:28px 32px;">
            {section_html}
          </td>
        </tr>

        <!-- Footer -->
        <tr>
          <td style="background:#f8f9fc;padding:16px 32px;border-top:1px solid #e9ecef;">
            <p style="margin:0;font-size:11px;color:#adb5bd;text-align:center;">
              Generated by Claude Haiku &nbsp;&middot;&nbsp; Articles sorted by relevance score
            </p>
          </td>
        </tr>

      </table>
    </td>
  </tr>
</table>
</body>
</html>"""


def send_digest(
    articles: list[dict],
    total_fetched: int = 0,
    source_count: int = 0,
) -> None:
    smtp_user = os.environ["SMTP_USER"]
    smtp_password = os.environ["SMTP_APP_PASSWORD"]
    recipients = [r.strip() for r in os.environ["SMTP_TO"].split(",")]

    today = date.today().strftime("%d %b %Y")
    subject = f"Enterprise AI Digest — {today} | {len(articles)} articles"

    html = build_html(articles, total_fetched, source_count)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = smtp_user
    msg["To"] = ", ".join(recipients)
    msg.attach(MIMEText(html, "html"))

    ctx = ssl.create_default_context()
    with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=ctx) as server:
        server.login(smtp_user, smtp_password)
        server.sendmail(smtp_user, recipients, msg.as_string())
